package com.enviro.assessment.grad001.fanelengubane.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

/**
 * Entity class representing a disposal guideline.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity
public class DisposalGuideline {

    /**
     * The unique identifier for the disposal guideline.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The guideline text.
     * This field cannot be blank.
     */
    @NotBlank(message = "Guideline cannot be blank")
    private String guideline;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGuideline() {
        return guideline;
    }

    public void setGuideline(String guideline) {
        this.guideline = guideline;
    }
}