package com.enviro.assessment.grad001.fanelengubane.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

/**
 * Entity class representing a recycling tip.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity
public class RecyclingTip {

    /**
     * The unique identifier for the recycling tip.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The tip text.
     * This field cannot be blank.
     */
    @NotBlank(message = "Tip cannot be blank")
    private String tip;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTip() {
        return tip;
    }

    public void setTip(String tip) {
        this.tip = tip;
    }
}