package com.enviro.assessment.grad001.fanelengubane.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

/**
 * Entity class representing a waste category.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity
public class WasteCategory {

    /**
     * The unique identifier for the waste category.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the waste category.
     * This field cannot be blank.
     */
    @NotBlank(message = "Category name cannot be blank")
    private String name;

    /**
     * A description of the waste category.
     * This field is optional.
     */
    private String description;

    // Getters and Setters

    /**
     * Gets the unique identifier of the waste category.
     *
     * @return the unique identifier of the waste category
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the waste category.
     *
     * @param id the unique identifier to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the waste category.
     *
     * @return the name of the waste category
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the waste category.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description of the waste category.
     *
     * @return the description of the waste category
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the waste category.
     *
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }
}