name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn compile

  cleanup:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up test database
        run: rm -f /Testing/robot_world_ewc10.db

  test:
    runs-on: ubuntu-latest
    needs: cleanup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package with Maven
        run: mvn package -Dmaven.test.skip=true

  create-image:
    runs-on: ubuntu-latest
    needs: package

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t enviro365:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag enviro365:latest ${{ secrets.DOCKER_USERNAME }}/enviro365:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/enviro365:latest

  upload:
    runs-on: ubuntu-latest
    needs: create-image
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload artifacts
        run: |
          mkdir -p public/$GITHUB_REF_NAME
          mv target/enviro365-0.0.1-SNAPSHOT.jar public/$GITHUB_REF_NAME/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: enviro365-artifacts
          path: public/